name: Podcast data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "5 11 * * 1,3,5" # Run at 04:05 on Monday, Wednesday, and Friday.

jobs:
  data_workflow:
    name: Data workflow
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-go@v5.0.1

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Podcast JSON files
        run: |
            python generate_podcast_json.py \
                --yaml-directory ../podcasts \
                --json-directory ../generated \
                --api-key ${{ secrets.PODCASTINDEX_API_KEY }} \
                --api-secret ${{ secrets.PODCASTINDEX_API_SECRET }}


      - name: GermanTechPodcasts Convert YAML to JSON
        run: ./GermanTechPodcasts convertYamlToJson --yaml-directory ../podcasts --json-directory ../generated

      - name: GermanTechPodcasts Gather additional podcast data
        run: ./GermanTechPodcasts collectPodcastData --api-key ${{ secrets.PODCASTINDEX_API_KEY }} --api-secret ${{ secrets.PODCASTINDEX_API_SECRET }} --json-directory ../generated

      - name: GermanTechPodcasts Convert JSON to README
        run: ./GermanTechPodcasts convertJsonToReadme --json-directory ../generated --readme-template ../assets/README.template --readme-output ../README.md

      - name: GermanTechPodcasts Render OPML file
        run: ./GermanTechPodcasts generateOpml --json-directory ../generated --opml-output ../podcasts.opml

      # Commit results back to repository
      - uses: stefanzweifel/git-auto-commit-action@v5.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Gnerate podcast data
          branch: main
          commit_user_name: Podcast Bot
          commit_user_email: podcastbot@bascodes.com
          commit_author: Podcast Bot <podcastbot@bascodes.com>

    #   - name: Trigger webpage to sync
    #     uses: peter-evans/repository-dispatch@v3.0.0
    #     with:
    #       token: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
    #       repository: EngineeringKiosk/webpage
    #       event-type: podcast-list-update